name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt môi trường Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cài đặt các thư viện phụ thuộc (Dependencies)
        run: npm install

  sast_scan:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Quét bảo mật bằng Semgrep
        run: |
          python3 -m pip install semgrep
          semgrep scan --config=auto

      - name: Quét bảo mật bằng SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=phamduclinh280106-sys_NodeGoat
            -Dsonar.organization=phamduclinh280106-sys


  sca_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Quét lỗ hổng thư viện bằng Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
        with:
          args: --severity-threshold=critical

  dast-scan:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Fix ZAP workspace permission
      run: |
        sudo chmod -R a+w "$GITHUB_WORKSPACE"

    - name: Start NodeGoat
      run: |
        docker compose up -d --build
        docker compose ps

    - name: Wait for NodeGoat
      run: |
        for i in {1..60}; do
          if curl -f http://localhost:4000; then
            echo "NodeGoat is ready"
            exit 0
          fi
          echo "Waiting for NodeGoat..."
          sleep 5
        done
        echo "NodeGoat did not start in time"
        docker compose logs
        exit 1

    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: 'http://localhost:4000'
        allow_issue_writing: false
        fail_action: false
        cmd_options: '-I'
